M48
; DRILL file {KiCad 9.0.7-9.0.7~ubuntu24.04.1} date 2026-02-26T22:41:37+1100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-02-26T22:41:37+11:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7-9.0.7~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X2.9878Y-3.7886
X3.2154Y-3.7886
M30
